### PR TITLE
[ #135964739] Report generation Ui and coding

### PR DESCRIPTION
**Pull request by MasterODST**
This is for the UI for the selection of reports

### CODE REVIEW

**Comment by TeckYong** [comment]
may i know what type of reports u are generating ?

**Comment by MasterODST** [comment]
The reports that will be generated will be a list of regular customers, list of products sold, a sales report 
and based on the recent review meeting a monthly sales report will be generated to

**Comment by TeckYong** [comment]
ok noted. thanks Daniel

**Review by TeckYong — APPROVED** [review]
well done.

**Review by chunweng428 — APPROVED** [review]

**Review by tanjunlem — APPROVED** [review]
Good coding

**Pull request merged**
