### PR TITLE
[#135964655]Add_New_Product

### PR DESCRIPTION
**Pull request by tanjunlem**
I am designing the add new product feature into the system. This feature allows the staff to add new products into the system. I still haven't complete it yet, But you guys can leave me some opinions or commends.

### CODE REVIEW

**Comment by TeckYong** [comment]
this feature is use by staff ?

**Comment by tanjunlem** [comment]
Yes its is used by staff.

**Review by TeckYong — APPROVED** [review]

**Comment by TeckYong** [comment]
Oic. Thanks

**Comment by chunweng428** [comment]
Nice UI design!

**Review by chunweng428 — APPROVED** [review]

**Comment by tanjunlem** [comment]
Thank you. I will keep do my best on this project

**Comment by MasterODST** [comment]
Intuitive UI design

**Review by MasterODST — APPROVED** [review]

**Pull request merged**
