### PR TITLE
[#135504925]Update_Customer_Details

### PR DESCRIPTION
**Pull request by tanjunlem**
I am creating update customer details form and function.

### CODE REVIEW

**Review by TeckYong — APPROVED** [review]
Well done.

**Comment by tanjunlem** [comment]
Thank you. I will keep continuing my task.

**Review by MasterODST — APPROVED** [review]

**Comment by MasterODST** [comment]
I just approved the work . You are very efficient

**Review by chunweng428 — APPROVED** [review]
Nice and well done.

**Pull request merged**
