### PR TITLE
[#135964725] Customer report

### PR DESCRIPTION
**Pull request by MasterODST**
It generates a report of all customers

### CODE REVIEW

**Review by tanjunlem — COMMENTED** [review]
This feature will be used by staff or customer ?

**Comment by MasterODST** [comment]
It will be for staff of course to help create reports to see the number of new and old customers in a certain period of time

**Review by TeckYong — CHANGES_REQUESTED** [review]
Should improve the algorithm to be more flexible

**Review by TeckYong — APPROVED** [review]

**Review by chunweng428 — APPROVED** [review]

**Review by tanjunlem — APPROVED** [review]
Good change

**Pull request merged**
